<?php
namespace Model\Repository\MainFunction;


class AssetsLoader
{
    private $BaseUrl;
    public function __construct(bool $MainAssets=true, bool $CustomAssets=false,string $CustomAssetsValue="localhost")
    {
        $this->BaseUrl="../../../..";
    }
    public function Loader(string $Extension,string $Name,string $UniqueUrl=null,$Local=false,string $UniqueType=null,string $ImageAlt=null,int $ImageWidth=null,int $ImageHeight=null,string $ImageStyle=null,string $ImageClass=null)
    {
        if ($UniqueUrl==null || $UniqueUrl=="")
        {
            if ($Extension=="js")
            {
                echo '<script src="'.$this->BaseUrl."/Script"."/".$Name.".".$Extension.'"></script>';
            }
            else if($Extension=="css")
            {
                echo '<link rel="stylesheet" type="text/css" href="'. $this->BaseUrl."/Style"."/".$Name.".".$Extension  .'">';
            }
            else if($Extension=="png"||$Extension=="jpg"||$Extension=="jpeg"||$Extension=="ico")
            {
                echo '<img src="'. $this->BaseUrl."/Content"."/".$Name.".".$Extension  .'" Width="'.$ImageWidth.'px" Height="'.$ImageHeight.'px" Class="'.$ImageClass.'" alt="'.$ImageAlt.'">';
            }
        }
        else
        {
            if ($UniqueType!=null)
            {
                if ($Local==true)
                {
                    if ($Extension=="js")
                    {
                        echo '<script src="'.$this->BaseUrl.$UniqueType."/Script/".$Name.".".$Extension.'"></script>';
                    }
                    else if($Extension=="css")
                    {
                        echo '<link rel="stylesheet" type="text/css" href="'. $this->BaseUrl.$UniqueType."/Style/".$Name.".".$Extension  .'">';
                    }
                    else if($Extension=="png"||$Extension=="jpg"||$Extension=="jpeg"||$Extension=="ico")
                    {
                        echo '<img src="'. $this->BaseUrl.$UniqueType."/Content/".$Name.".".$Extension  .'" Width="'.$ImageWidth.'px" Height="'.$ImageHeight.'px" Class="'.$ImageClass.'" Style="'.$ImageStyle.'" alt="'.$ImageAlt.'">';
                    }
                }
                else
                {
                    echo '<link href="'.$UniqueUrl."/".$Name.".".$UniqueType.'">';
                }
            }
            else
            {
                if ($Local==false || $Local=="")
                {
                    if ($Extension=="js")
                    {
                        echo '<script src="'.$UniqueUrl."/".$Name.".".$Extension.'"></script>';
                    }
                    else if($Extension=="css")
                    {
                        echo '<link rel="stylesheet" type="text/css" href="'.$UniqueUrl."/".$Name.".".$Extension.'">';
                    }
                    else if($Extension=="png"||$Extension=="jpg"||$Extension=="jpeg"||$Extension=="ico")
                    {
                        echo '<img src="'.$UniqueUrl."/".$Name.".".$Extension.'" Width="'.$ImageWidth.'px" Height="'.$ImageHeight.'px" Class="'.$ImageClass.'" Style="'.$ImageStyle.'" alt="'.$ImageAlt.'">';
                    }
                }
                elseif ($Local==true)
                {
                    if ($Extension=="js")
                    {
                        echo '<script src="'.$this->BaseUrl."/Script/".$UniqueUrl."/".$Name.".".$Extension.'"></script>';
                    }
                    else if($Extension=="css")
                    {
                        echo '<link rel="stylesheet" type="text/css" href="'.$this->BaseUrl."/Style/".$UniqueUrl."/".$Name.".".$Extension.'">';
                    }
                    else if($Extension=="png"||$Extension=="jpg"||$Extension=="jpeg"||$Extension=="ico")
                    {
                        echo '<img src="'.$this->BaseUrl."/Content/".$UniqueUrl."/".$Name.".".$Extension.'" Width="'.$ImageWidth.'px" Height="'.$ImageHeight.'px" Class="'.$ImageClass.'" Style="'.$ImageStyle.'" alt="'.$ImageAlt.'">';
                    }
                }
                else
                {
                    if ($Extension=="js")
                    {
                        echo '<script src="'.$UniqueUrl."/".$Name.".".$Extension.'"></script>';
                    }
                    else if($Extension=="css")
                    {
                        echo '<link rel="stylesheet" type="text/css" href="'.$UniqueUrl."/".$Name.".".$Extension.'">';
                    }
                    else if($Extension=="png"||$Extension=="jpg"||$Extension=="jpeg"||$Extension=="ico")
                    {
                        echo '<img src="'.$UniqueUrl."/".$Name.".".$Extension.'" Width="'.$ImageWidth.'px" Height="'.$ImageHeight.'px" Style="'.$ImageStyle.'" alt="'.$ImageAlt.'">';
                    }
                }
            }
        }
    }
}