<?php
/**
 * Created by PhpStorm.
 * User: farva
 * Date: 17/03/2018
 * Time: 02:55 PM
 */

namespace Middleware\Important;
use Core\Configurations\Routing;
use Core\Security\Check;
use Core\Watcher\Basement;


class Security
{
    protected $CoreSecurity;
    protected $Configurations;
    public function __construct()
    {
        Basement::MinVersion();
        Check::SecureProtocol(Routing::$SecureProtocol);
    }

}