<?php
/**
 * Created by PhpStorm.
 * User: farva
 * Date: 17/03/2018
 * Time: 02:55 PM
 */

namespace Middleware\Important;
use Core\Configurations\Routing;
use Core\Security\Check;
use Core\Watcher\Basement;


class Security
{
    protected $CoreSecurity;
    protected $Configurations;
    public function __construct()
    {
        Basement::MinVersion();
        Check::SecureProtocol(Routing::$SecureProtocol);
        self::CleanString($_REQUEST);
    }
    private static function CleanString($Request)
    {
        $bad = array("content-type","href","'",'"','script','>','<','<script>','</script>');

        foreach ($Request as $Key => $Value)
        {
            foreach ($bad as $mis) {
                if (str_contains($Value, $mis)) {

                    $_REQUEST[$Key] = str_replace($mis, " ", $Value);
                }
            }
        }
    }

}