<?php
/**
 * Created by PhpStorm.
 * User: farva
 * Date: 13/04/2018
 * Time: 06:33 PM
 */

namespace Model\Logic\MainLogic;


//use MailerLiteApi\Api\Subscribers;
//use MailerLiteDocs\cMailerLite;
use Model\Logic\DataContract;
use Model\Repository\MainFunction\UserRepository;
use Route\Show\View;

final class UserFunction implements DataContract
{
    private $User;
    //private static $Subscriber;
    private $Viewbag;
    private $ID = 0;

    public function __construct()
    {
        $this->User = new UserRepository();
        //self::$Subscriber = new cMailerLite();
    }

    public function New()
    {
        /*self::$Subscriber = new cMailerLite();
        if (isset($_POST) && isset($_POST['submit']))
        {
            $response = self::$Subscriber::NewSubscriber($_POST['Email'],$_POST['Firstname'],$_POST['Lastname'],$_POST['Company']);
            if ($response->date_created!=null && $response->date_created!="")
            {
                view::Process('Panel.Admin.Subs');
            }
            else
            {
                view::Process('Panel.Admin.NewSubs');
            }
        }
        else
        {
            view::Process('Panel.Admin.NewSubs');
        }*/

        /*setcookie("Username","",Time()-36000);
        if (isset($_POST['submit']))
        {
            if (empty($_POST['username']) || empty($_POST['password']))
            {
                $error = "Username or Password is invalid";
            }
            else
            {

                $Username = $_POST['username'];
                $Password = $_POST['password'];
                $Val = $this->User->FindByUser($Username);
                $uResult = $this->User->Username($Username);
                $pResult = $this->User->Password($Password);
                if ($uResult == 1 && $pResult==1)
                {
                    header("Location: /Panel");
                    setcookie("Username",$Val['Values']['user_Firstname'],0);

                }
                else
                {
                    $error = "Username or Password is invalid";
                    header("Location: /Login");
                }
            }
        }*/
    }

    public function Update($QuerryString)
    {

    }

    public function Profile()
    {
        if (isset($_POST['submit']) == true) {
            $DefaultDirectory = "Content/Shared/Profile/Dp";
            $FileType = "." . substr($_FILES["Image"]["type"], 6);
            $Firstname = $_POST['Firstname'];
            $Lastname = $_POST['Lastname'];
            $Nickname = $_POST['Nickname'];
            $Username = $_POST['Username'];
            $Password = $_POST['Password'] == $_POST['Password-Verf'] && $_POST['Password'] != "" ? password_hash($_POST['Password'], 1) : "";
            $Email = $_POST['Email'];
            $Phone = $_POST['Phone'];
            $Image = $_FILES['Image']['name'];
            $Bio = $_POST['Bio'];
            if ($Image != null) {
                $TargetFile = $DefaultDirectory . basename($_POST['Firstname'] . $FileType);
                if (file_exists($TargetFile)) {
                    unlink($TargetFile);
                    $NewTargetFile = $DefaultDirectory . basename($_POST['Firstname'] . $FileType);
                    if (move_uploaded_file($_FILES["Image"]['tmp_name'], $NewTargetFile)) {
                        $Update = $this->User->Update($Firstname, $Lastname, $Nickname, $Username, $Password, $Email, $Phone, $NewTargetFile, $Bio);
                        if ($Update['Rows'] == 1) {
                            header("Location: /Panel");
                        } else {
                            header("Location: /Panel/Profile");

                        }

                    } else {
                        header("Location: /Panel/Profile");

                    }
                } else {
                    if (move_uploaded_file($_FILES["PostImage"]['tmp_name'], $TargetFile)) {
                        $Update = $this->User->Update($Firstname, $Lastname, $Nickname, $Username, $Password, $Email, $Phone, $TargetFile, $Bio);
                        if ($Update['Rows'] == 1) {
                            header("Location: /Panel");
                        } else {
                            header("Location: /Panel/Profile");

                        }

                    } else {
                        echo "Image did not upload!";
                        header("Location: /Panel/Profile");

                    }
                }
            } else {
                $Update = $this->User->Update($Firstname, $Lastname, $Nickname, $Username, $Password, $Email, $Phone, "Content/Shared/Profile/Dp/Avatar.png", $Bio);
                if ($Update['Rows'] == 1) {
                    header("Location: /Panel");
                } else {
                    header("Location: /Panel/Profile");

                }
            }
        } else {
            header("Location: /Panel/Profile");
        }
    }

    public function Delete($QuerryString)
    {

    }

    public function Show()
    {
        /*self::$Subscriber= new cMailerLite();


        self::$Subscriber::Subscribers();
        if (self::$Subscriber::Subscribers()!=null)
        {
            foreach (self::$Subscriber::Subscribers() as $Subscriber)
            {
                $email= get_object_vars($Subscriber->fields['0']);
                $fname = get_object_vars($Subscriber->fields['1']);
                $lname= get_object_vars($Subscriber->fields['2']);
                $phone= get_object_vars($Subscriber->fields['6']);
                //var_dump($fname['value']);
                self::$Viewbag = ['UserInfo'=>[
                    'fname'=> $fname['value'],
                    'lname'=>$lname['value'],
                    'email'=>$email['value'],
                    'phone'=>$phone['value']
                ]];
                self::$ID++;
                var_dump(self::$Viewbag['UserInfo']);

            }
            view::Process('Panel.Admin.Subs',self::$Viewbag);

        }
        else
        {
            view::Process('Panel.Admin.Subs');
        }*/
    }

    public function Login()
    {
        if (empty($_POST['username']) || empty($_POST['password'])) {
            $Viewbag = ['Error' => 'یک نام کاربری و رمزینه صحیح وارد نمایید'];
            View::Process("Panel.User.Login", $Viewbag);
        } else {
            $Token = rand(5000, 1000000) . "-" . rand(5000, 1000000) . "-" . rand(5000, 1000000);
            $Username = addslashes($_POST['username']);
            $Password = addslashes($_POST['password']);
            $Login = $this->User->Login($Username, $Password, $Token);
            if ($Login['Rows'] == "11") {
                setcookie("Username", $Login['Values']['u_Username'], time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                setcookie("Firstname", $Login['Values']['u_FName'], time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                setcookie("LoginToken", password_hash($Token, 1), time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                setcookie("lcsrn_Validation", password_hash("true", 1), time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                header("Location: /Panel");
            } else {
                setcookie("lcsrn_Validation", password_hash("false", 1), time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                $Viewbag = ['Error' => 'نام کاربری یا گذرواژه اشتباه است.', 'Result' => $Login['Values']];
                View::Process("Panel.User.Login", $Viewbag);
            }
        }
    }

    public function LockScreen()
    {
        if (!isset($_COOKIE['Username']) && !($_COOKIE['Username'] != null || $_COOKIE['Username'] != "")) {
            header("Location: /Login");

        } else {
            if (isset($_POST['submit'])) {
                if (empty($_POST['password'])) {
                    setcookie("Error", "گذرواژه نباید خالی باشد", 0, "", $_SERVER['HTTP_HOST']);
                    setcookie("lcsrn_Validation", password_hash("false", 1), time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                    header("Location: /Lock");
                } else {

                    $Username = $_COOKIE['Username'];
                    $Token = rand(5000, 1000000) . "-" . rand(5000, 1000000) . "-" . rand(5000, 1000000);
                    $Password = addslashes($_POST['password']);
                    $Login = $this->User->Login($Username, $Password, $Token);
                    if ($Login['Rows'] == "11") {
                        setcookie("Username", $Login['Values']['u_Username'], time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                        setcookie("LoginToken", password_hash($Token, 1), time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                        if (password_verify("false", $_COOKIE['lcsrn_Validation'])) {
                            setcookie("lcsrn_Validation", password_hash("true", 1), time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST']);
                            header("Location: /Panel");
                        } else {
                            header("Location: /Login");
                        }
                    } else {
                        setcookie("Error", "گذرواژه اشتباه است.", 0);
                        setcookie("lcsrn_Validation", password_hash("false", 1), time() + 60 * 60 * 24 * 365, "", $_SERVER['HTTP_HOST'], true, true);
                        header("Location: /Lock");
                    }
                }
            }
        }
    }
}