<?php
if (isset($_POST['Amount']) && isset($_POST['Email']) && isset($_POST['Phone']) && isset($_POST['Order']) && isset($_POST['Name']) && isset($_POST['Submit']))
{
$MerchantID = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'; //Required
$Amount = "5000"; //Amount will be based on Toman - Required
$Description = ""; // Required $_POST['Order']."\n".isset($_POST['Description'])?$_POST['Description'] : ""
$Email = "info@miladzandi.ir"; // Optional
$Mobile =  "09201007320"; // Optional

$CallbackURL = 'https://www.eastcloud.ir/Verify'; // Required


$client = new SoapClient('https://sandbox.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);

$result = $client->PaymentRequest(
[
'MerchantID' => $MerchantID,
'Amount' => $Amount,
'Description' => $Description,
'Email' => $Email,
'Mobile' => $Mobile,
'CallbackURL' => $CallbackURL,
]
);

//Redirect to URL You can do it also by creating a form
if ($result->Status == 100) {
Header('Location: https://sandbox.zarinpal.com/pg/StartPay/'.$result->Authority);
} else {
echo'ERR: '.$result->Status;
}
}
else
{
\Route\Show\View::Process("Payment.Zarinpal.Pay");
}