<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="Xenon Boostrap Admin Panel" />
	<meta name="author" content="" />
    <link rel="shortcut icon" type="image/x-icon" href="../../../Content/Shared/Logo.png" id="favicon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
	<title>SIMPLIST - LOCKSCREEN</title>

    <?php
    $error=''; // Variable To Store Error Message
    if (!isset($_COOKIE['Username']) &&!($_COOKIE['Username']!=null||$_COOKIE['Username']!=""))
    {
        header("Location: /Login");

    }
    else
    {
    if (isset($_POST['submit']))
    {
        if ( empty($_POST['password']))
        {
            $error = "Username or Password is invalid";
        }
        else
        {

            $Username = $_COOKIE['Username'];

            $Password = $_POST['password'];
            $Data = new Model\Repository\MainFunction\UserRepository();
            $Val = $Data->FindByUser($Username);
            $uResult = $Data->Username($Username);
            $pResult = $Data->Password($Password);
            setcookie("Username","",Time()-36000);
            if ($pResult==1)
            {
                header("Location: /Panel");
                setcookie("Username",$Val['Values']['user_Firstname'],0);

            }
            else
            {
                $error = "Username or Password is invalid";
                header("Location: /Panel/Sleep");
            }
        }
    }
    }
    $Adder = new Core\Requirement\oLoad("../../..","Style/Panel","Script/Panel","Style/Panel");
    $Adder->Loader("css","fonts/fontawesome/css/font-awesome.min");
    $Adder->Loader("css","fonts/linecons/css/linecons");
    $Adder->Loader("css","bootstrap");
    $Adder->Loader("css","xenon-core");
    $Adder->Loader("css","xenon-forms");
    $Adder->Loader("css","xenon-components");
    $Adder->Loader("css","xenon-skins");
    $Adder->Loader("css","custom");
    $Adder->Loader("css","mytest");
    $Adder->Loader("js","jquery-1.11.1.min");
    $Adder->Loader("js","html5shiv.min","https://oss.maxcdn.com/html5shiv/3.7.2/",false);
    $Adder->Loader("js","respond.min","https://oss.maxcdn.com/respond/1.4.2/");
    ?>
	
</head>
<body class="page-body lockscreen-page" >

	<div class="login-container" dir="rtl" style="font-family: IrRoya">
	
		<div class="row" dir="rtl" >
		
			<div class="col-sm-7">
				

				
				<form role="form" method="post" id="lockscreen" action="" class="lockcreen-form">
					
					<div class="user-thumb">
						<a href="#">
                            <img src="../../../../Content/Shared/Profile/Milad.png" class="img-responsive img-circle" />

                        </a>
					</div>
					
					<div class="form-group">
						<h3><?php echo $_COOKIE['Username']; ?> خوش آمدی!</h3>
						<p>برای دسترسی به صفحه مدیریت رمز خود را وارد کنید.</p>
                        <a href="/Login" style="color: #fff;" >
                            <i class="fa-power-off"></i>
                        <span>خروج</span>
                        </a>
						<div class="input-group">
							<input type="password" class="form-control input-dark" name="password" id="password" placeholder="گذرواژه" />
							<span class="input-group-btn">
								<button type="submit" name="submit" id="submit" class="btn btn-primary">ورود</button>
							</span>
						</div>
					</div>
					
				</form>
				
			</div>
			
		</div>
		
	</div>



	<!-- Bottom Scripts -->
    <?php
    $Adder->Loader("js","bootstrap.min");
    $Adder->Loader("js","TweenMax.min");
    $Adder->Loader("js","resizeable");
    $Adder->Loader("js","joinable");
    $Adder->Loader("js","xenon-api");
    $Adder->Loader("js","xenon-toggles");
    $Adder->Loader("js","jquery-validate/jquery.validate.min");
    $Adder->Loader("js","toastr/toastr.min");
    $Adder->Loader("js","xenon-custom");
    $Adder->Loader("js","bootstrap.min");
    ?>

</body>
</html>