<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Xenon Boostrap Admin Panel"/>
    <meta name="author" content=""/>
    <link rel="shortcut icon" type="image/x-icon" href="../../../Content/Shared/Logo.png" id="favicon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
    <title>SIMPLIST - SIGNUP</title>

    <?php
    session_start();
    $error = ''; // Variable To Store Error Message

    setcookie("Username", "", Time() - 36000);
    if (isset($_POST['submit'])) {
        if (empty($_POST['username']) || empty($_POST['password'])) {
            $error = "Username or Password is invalid";
        } else {

            $Username = $_POST['username'];
            $Email = $_POST['email'];
            $Name = $_POST['name'];
            $Phone = $_POST['phone'];
            $Password = $_POST['password'];
            $Data = new Model\Repository\MainFunction\UserRepository();
            $Val1 = $Data->FindByUser($Username);
            $Val2 = $Data->FindByEmail($Email);

            if ($Val2 == 1 && $Val1 == 1) {
                header("Location: /Signup");

            } else {

                header("Location: /Login");
            }
        }
    }
    $Add = new Core\Requirement\oLoad("../../..", "Style/Panel", "Script/Panel", "Style/Panel");
    $Add->Loader("css", "fonts/fontawesome/css/font-awesome.min");
    $Add->Loader("css", "fonts/linecons/css/linecons");
    $Add->Loader("css", "bootstrap.min", "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css", false);
    $Add->Loader("css", "mytest");
    ?>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->


</head>
</head>
<body>
<div style="margin-top:100px;margin-left:100px;margin-right:100px;">
    <form method="Post" role="form" action="">
        <div class="form-group">
            <label for="username">Email address</label>
            <input type="email" class="form-control" name="email" id="email" required placeholder="Enter email address">
        </div>
        <div class="form-group">
            <label for="username">National Code</label>
            <input type="number" class="form-control" name="username" id="username" required placeholder="Enter national code">
        </div>
        <div class="form-group">
            <label for="username">Full Name</label>
            <input type="text" class="form-control" name="name" id="name" required placeholder="Enter full name">
        </div>
        <div class="form-group">
            <label for="username">Phone Number</label>
            <input type="tel" class="form-control" name="phone" id="phone" required placeholder="Enter phone number">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" required id="password" placeholder="Password">
        </div>
        <button type="submit" name="submit" id="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</body>
</html>