<?php

namespace Controller\Panel;


use Model\Logic\MainLogic\PostFunction;
use Model\Logic\MainLogic\UrlFunction;
use Model\Logic\MainLogic\UserFunction;
use Model\Repository\MainFunction\UserRepository;
use Route\Show\View;

class AdminController
{
    private $Post;
    private $User;
    private $Url;
    public function __construct()
    {
        $this->User= new UserRepository();
    }

    public function Index()
    {
        $Viewbag=['UserInfo'=>$this->User->FindByUser($_COOKIE['Username'])['Values']];
        View::Process("Panel.Admin.Panel",$Viewbag);
    }
    public function Profile()
    {
		$Viewbag = ['UserInfo' => $this->User->FindByUser($_COOKIE['Username'])['Values']];

     	if (isset($_POST))
		{
			UserFunction::Profile();
		}
		else
		{
			View::Process("Panel.Admin.Profile", $Viewbag);
		}
    }

    public function Users()
    {
    	$Data = new \Model\Repository\MainFunction\UserRepository();
		$Viewbag = ['UserInfo'=>$Data->GetUsers()];

		View::Process("Panel.Admin.Users",$Viewbag);
    }

    public function NewPost()
    {
		PostFunction::New();
        View::Process("Panel.Admin.NewPost");
    }
    public function Post()
    {
		$Viewbag = ['PostInfo'=>PostFunction::Show()];
		View::Process("Panel.Admin.Posts",$Viewbag);
    }
    public function PostDelete($QuerryString)
    {
		PostFunction::Delete($QuerryString);
    }
    public function PostUpdate($QuerryString)
    {
        PostFunction::Update($QuerryString);
    }

    public function NewUrl()
    {
		UrlFunction::New();
		View::Process("Panel.Admin.NewUrl");
    }
    public function Url()
    {
		$Viewbag = ['UrlInfo'=>UrlFunction::Show()];
        View::Process("Panel.Admin.Url",$Viewbag);
    }
    public function UrlDelete($QuerryString)
    {
		UrlFunction::Delete($QuerryString);
    }
    public function UrlUpdate($QuerryString)
    {
		UrlFunction::Update($QuerryString);

    }
}