<?php


namespace Controller\Panel;


use Model\Logic\MainLogic\UserFunction;
use Route\Show\View;

class UserController
{
    private $Data;
    public function __construct()
    {
       $this->Data= new UserFunction();

    }
    public function Login()
    {
    	$this->Data->Login();
		View::Process("Panel.User.Login");
    }
    public function Signup()
    {
        View::Process("Panel.User.Signup");
    }
	public function Lock()
	{
		$this->Data->LockScreen();
		View::Process("Panel.User.Lockscreen");
	}
}