<?php


namespace Controller\Panel;


use Model\Logic\MainLogic\UserFunction;
use Route\Show\View;

class UserController
{
    private $Data;
    public function __construct()
    {
       $this->Data= new UserFunction();

    }
    public function Login()
    {
        if (isset($_POST['submit']))
        {
            $this->Data->Login();
        }
        else
        {
            if  (isset($_GET['Logout']) && $_GET['Logout'] == "True")
            {
                if (isset($_COOKIE['Username']))
                {
                    setcookie("Username","",time()-3600,"",$_SERVER['HTTP_HOST'],true);
                    $Viewbag = ['Success'=>'YOu Logged out successfully!!'];
                    View::Process("Main.Home.Index",$Viewbag);

                }
                else
                {
                    View::Process("Panel.User.Login");
                }
            }
            else
            {
                View::Process("Panel.User.Login");
            }
        }
    }
    public function Signup()
    {
        View::Process("Panel.User.Signup");
    }
	public function Lock()
	{
		$this->Data->LockScreen();
		View::Process("Panel.User.Lockscreen");
	}
}