<?php


namespace Controller\Panel;


use Model\Repository\MainFunction\UserRepository;
use Route\Show\View;

class UserController
{
    private $Data;
    public function __construct()
    {
       $this->Data= new UserRepository();
    }
    public function Login()
    {
        $Item= $this->Data->Find(1);
        View::Process("Panel.User.Login",compact('Item'));
    }
    public function Signup()
    {
        View::Process("Panel.User.Signup");
    }
    public function Sleep()
    {
        View::Process("Panel.User.Lockscreen");
    }
    public function ForgetPassword()
    {
        View::Process("Panel.User.ForgetPassword");
    }
    public function Dashboard()
    {
        $Item= $this->Data->Find(1);
        View::Process("Panel.User.Dashboard",compact('Item'));
    }
    public function Maps()
    {
        View::Process("Panel.User.Maps");
    }
}