<?php $Add = new Core\Requirement\oLoad("../../..","Style","Script","Content"); ?>

<!--  Footer -->
<footer class="container py-5">
    <div class="row">
        <div class="col-12 col-md">
            <a href="http://eastcloud.ir" target="_blank"><?php $Add->Loader("png","eastCloud","Shared",true,false,"eastCloud",24,24); ?></a>
            <small class="d-block mb-3 text-muted">© 2017-2018</small>
        </div>
        <div class="col-6 col-md">
            <h5>New Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/Feacture/Driver">Choose Driver</a></li>
                <li><a class="text-muted" href="/Feacture/Hash">Make it Hash!</a></li>
                <li><a class="text-muted" href="/Feacture/SUS">Sunshine Sec</a></li>
                <li><a class="text-muted" href="/Feacture/Observer">Observer</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources & Versions</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/Res">Resource</a></li>
                <li><a class="text-muted" href="/Download/Versions">Stable Versions</a></li>
                <li><a class="text-muted" href="/Dev/Versions">Dev Versions</a></li>
                <li><a class="text-muted" href="/Download/Versions/Latest">Download Lates</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Develop</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="https://github.com/miladxandi/Simplist">Github</a></li>
                <li><a class="text-muted" href="/Documentation/Education">Education</a></li>
                <li><a class="text-muted" href="/Documentation">Documentations</a></li>
                <li><a class="text-muted" href="/Services">Services</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/Team">Team</a></li>
                <li><a class="text-muted" href="/Locations">Locations</a></li>
                <li><a class="text-muted" href="/Privacy">Privacy</a></li>
                <li><a class="text-muted" href="/Terms">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>
</body>
</html>