<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Xenon Boostrap Admin Panel" />
    <meta name="author" content="" />
    <link rel="shortcut icon" type="image/x-icon" href="../../../Content/Shared/Logo.png" id="favicon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
    <?php
    if (!isset($_COOKIE['Username']) &&!($_COOKIE['Username']!=null||$_COOKIE['Username']!=""))
    {
        header("Location: /Login");

    }
    $Adder = new Core\Requirement\oLoad("../../..","Style/Panel","Script/Panel","Content/");
    $Adder->Loader("css","fonts/fontawesome/css/font-awesome.min");
    $Adder->Loader("css","fonts/linecons/css/linecons");
    $Adder->Loader("css","bootstrap");
    $Adder->Loader("css","xenon-core");
    $Adder->Loader("css","xenon-forms");
    $Adder->Loader("css","xenon-components");
    $Adder->Loader("css","xenon-skins");
    $Adder->Loader("css","custom");
    $Adder->Loader("css","mytest");
    $Adder->Loader("js","jquery-1.11.1.min");
    $Adder->Loader("js","html5shiv.min","https://oss.maxcdn.com/html5shiv/3.7.2/",false);
    $Adder->Loader("js","respond.min","https://oss.maxcdn.com/respond/1.4.2/");
    ?>



