
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="object" property="og:type">
    <meta content="Simplist is a free & open-source framework for developing, creating & designing online blogs simply." name="description">
    <meta name="keywords" content="PHP
     Simplist
     Framework
     PHP Framework
     Simplist Framework
     Simplist PHP Framework
     Simplist PHP
     Simplist Site
     Simple
     Simple Site
     Web Designer
     سیمپلیست
     فریمورک PHP
     فریمورک پی اچ پی
     فریمورک سیمپلیست
     طراحی وب
     طراحی وب بدون دانش برنامه نویسی">
    <meta content="origin-when-cross-origin" name="referrer">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
    <link rel="shortcut icon" type="image/x-icon" href="../../../Content/Shared/Logo.png" id="favicon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../Content/Shared/Logo.png">
<?php
$Add = new Core\Requirement\oLoad("../../..", "Style/Panel", "Script/Panel", "Style/Panel");
$Add->Loader("css","main");
$Add->Loader("css","Logos","Shared",true);
$Add->Loader("css","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css");
$Add->Loader("js","main");
$Add->Loader("js","jquery-3.2.1.slim.min","https://code.jquery.com");
$Add->Loader("js","popper.min","https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd");
$Add->Loader("js","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js");
?>