</head>
<body class="page-body right-sidebar DefinedFonts" dir="rtl" style="font-family: BNazanin">
<div class="settings-pane">

    <a href="#" data-toggle="settings-pane" data-animate="true">
        &times;
    </a>

    <div class="settings-pane-inner">

        <div class="row">

            <div class="col-md-4">

                <div class="user-info">

                    <div class="user-image">
                        <a href="extra-profile.html">
                            <img src="../../../Content/Shared/Profile/میلاد.png" class="img-responsive img-circle" />
                        </a>
                    </div>

                    <div class="user-details">

                        <h3>
                            <a href="extra-profile.html" class="DefinedFonts">میلاد زندی</a>

                            <!-- Available statuses: is-online, is-idle, is-busy and is-offline -->
                            <span class="user-status is-online DefinedFonts"></span>
                        </h3>

                        <p class="user-title DefinedFonts">توسعه دهنده وب</p>

                        <div class="user-links">
                            <a href="extra-profile.html" class="btn btn-primary DefinedFonts">ویرایش مشخصات</a>
                            <a href="extra-profile.html" class="btn btn-success DefinedFonts">ارتقاء</a>
                        </div>

                    </div>

                </div>

            </div>

            <div class="col-md-8 link-blocks-env">

                <div class="links-block left-sep">
                    <h4>
                        <span class="DefinedFonts">اطلاعیه</span>
                    </h4>

                    <ul class="list-unstyled">
                        <li>
                            <input type="checkbox" class="cbr cbr-primary DefinedFonts" checked="checked" id="sp-chk1" />
                            <label for="sp-chk1" class="DefinedFonts">پیام ها</label>
                        </li>
                        <li>
                            <input type="checkbox" class="cbr cbr-primary DefinedFonts" checked="checked" id="sp-chk2" />
                            <label for="sp-chk2" class="DefinedFonts">رویدادها</label>
                        </li>
                        <li>
                            <input type="checkbox" class="cbr cbr-primary DefinedFonts" checked="checked" id="sp-chk3" />
                            <label for="sp-chk3" class="DefinedFonts">به روز رسانی</label>
                        </li>
                        <li>
                            <input type="checkbox" class="cbr cbr-primary DefinedFonts" checked="checked" id="sp-chk4" />
                            <label for="sp-chk4" class="DefinedFonts">زمان آپلود سرور</label>
                        </li>
                    </ul>
                </div>

                <div class="links-block left-sep">
                    <h4>
                        <a href="#">
                            <span class="DefinedFonts">میز کمک</span>
                        </a>
                    </h4>

                    <ul class="list-unstyled">
                        <li>
                            <a href="#" class="DefinedFonts">
                                <i class="fa-angle-right"></i>
                                مرکز پشتیبانی
                            </a>
                        </li>
                        <li>
                            <a href="#" class="DefinedFonts">
                                <i class="fa-angle-right"></i>
                                ارسال بلیط
                            </a>
                        </li>
                        <li>
                            <a href="#" class="DefinedFonts">
                                <i class="fa-angle-right"></i>
                                پروتکل دامنه
                            </a>
                        </li>
                        <li>
                            <a href="#" class="DefinedFonts">
                                <i class="fa-angle-right"></i>
                                شرایط استفاده از خدمات
                            </a>
                        </li>
                    </ul>
                </div>

            </div>

        </div>

    </div>

</div>