<?php \View\View\Shared\PanelLayouts::_Header(); ?>
<title>SIMPLIST - New Post</title>

<?php


if (isset($_POST['submit'])) {

    $Data = new \Model\Repository\MainFunction\PostRepository();
    $Name = $_POST["PostName"];
    $Url = $_POST["PostUrl"];
    $Summary = substr($_POST["PostContent"], 0,150)." ...";
    $Content = $_POST["PostContent"];
    $Author = $_POST["PostAuthor"];
    $Insert = $Data->Insert($Name,$Url,$Summary,$Content,$Author,$Image);
    if ($Insert == 1) {
        header("Location: /Panel/NewPost");
    } else {
        header("Location: /Panel/NewPost");

    }
}

?>
</head>
<?php \View\View\Shared\PanelLayouts::_Menu(); ?>




<div style="margin-top:100px;margin-left:100px;margin-right:100px;">
    <form method="Post" role="form" action="" enctype="multipart/form-data">

        <div class="form-group">
            <label for="PostName">Post Name</label>
            <input type="text" class="form-control" name="PostName" id="PostName" required
                   placeholder="Title">
        </div>
        <div class="form-group">
            <label for="PostUrl">Post Url</label>
            <input type="text" class="form-control" name="PostUrl" id="PostUrl" required
                   placeholder="Specified URL">
        </div>
        <div class="form-group">
            <label for="PostContent">Content</label>
            <textarea class="form-control" name="PostContent" id="PostContent" required placeholder="Content"></textarea>
        </div>
        <div class="form-group">
            <label for="PostAuthor">Author</label>
            <input type="text" class="form-control" name="PostAuthor" id="PostAuthor" readonly value="<?php echo $_COOKIE['Firstname']; ?>"  required
                   placeholder="Enter author name">
        </div>
        <button type="submit" name="submit" id="submit" class="btn btn-primary">Post</button>


</form>
</div>
<?php \View\View\Shared\PanelLayouts::_Footer(); ?>
