<?php
return[
    '/' => [
        'target' => 'Main.Home.Index',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>'Main.Home.Index'

    ],
    '/Aboutus' => [
        'target'=>'Main.Home.Aboutus',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>'Main.Home.Aboutus'

    ],
    '/aboutus' => [
        'target'=>'Main.Home.Aboutus',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>'Main.Home.Aboutus'

    ],
    '/NotFound' => [
        'target'=>'Helper.Error.Error404',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/InternalError' => [
        'target'=>'Helper.Error.Error500',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Badrequest' => [
        'target'=>'Helper.Error.Error402',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Forbidden' => [
        'target'=>'Helper.Error.Error403',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/MethodNotAllowed' => [
        'target'=>'Helper.Error.Error405',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Content' => [
        'target'=>'Helper.Error.NotFound',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/content' => [
        'target'=>'Helper.Error.NotFound',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/login' => [
        'target'=>'Panel.User.Login',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Login' => [
        'target'=>'Panel.User.Login',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Signup' => [
        'target'=>'Panel.User.Signup',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/signup' => [
        'target'=>'Panel.User.Signup',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Documentation'=>[
        'target'=>'Main.Home.Documentation',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>''
    ]
];