<?php
return[
    '/' => [
        'target' => 'Main.HomeController.Index',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''

    ],
    '/Aboutus' => [
        'target'=>'Main.HomeController.Aboutus',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''

    ],
    '/aboutus' => [
        'target'=>'Main.HomeController.Aboutus',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''

    ],
    '/Panel' => [
        'target'=>'Panel.UserController.Dashboard',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/panel' => [
        'target'=>'Panel.UserController.Dashboard',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/NotFound' => [
        'target'=>'Helper.ErrorController.Error404',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/InternalError' => [
        'target'=>'Helper.ErrorController.Error500',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Badrequest' => [
        'target'=>'Helper.ErrorController.Error402',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Forbidden' => [
        'target'=>'Helper.ErrorController.Error403',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/MethodNotAllowed' => [
        'target'=>'Helper.ErrorController.Error405',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Content' => [
        'target'=>'Helper.ErrorController.NotFound',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/content' => [
        'target'=>'Helper.ErrorController.NotFound',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/login' => [
        'target'=>'Panel.UserController.Login',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Login' => [
        'target'=>'Panel.UserController.Login',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Signup' => [
        'target'=>'Panel.UserController.Signup',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/signup' => [
        'target'=>'Panel.UserController.Signup',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Panel/Maps' => [
        'target'=>'Panel.UserController.Maps',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Panel/maps' => [
        'target'=>'Panel.UserController.Maps',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Panel/Sleep' => [
        'target'=>'Panel.UserController.Sleep',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Panel/sleep' => [
        'target'=>'Panel.UserController.Sleep',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Val' => [
        'target'=>'Panel.UserController.Val',
        'gverb'=> '',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Panel/Tables' => [
        'target'=>'Panel.UserController.Tables',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Panel/tables' => [
        'target'=>'Panel.UserController.Tables',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
];