<?php
return[
    '/' => [
        'target' => 'Main.Home.Index',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>'Main.Home.Index'

    ],
    '/Aboutus' => [
        'target'=>'Main.Home.Aboutus',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>'Main.Home.Aboutus'

    ],
    '/aboutus' => [
        'target'=>'Main.Home.Aboutus',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>'Main.Home.Aboutus'

    ],
    '/NotFound' => [
        'target'=>'Helper.Error.Error404',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/InternalError' => [
        'target'=>'Helper.Error.Error500',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Badrequest' => [
        'target'=>'Helper.Error.Error402',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Forbidden' => [
        'target'=>'Helper.Error.Error403',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/MethodNotAllowed' => [
        'target'=>'Helper.Error.Error405',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/Content' => [
        'target'=>'Helper.Error.NotFound',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/content' => [
        'target'=>'Helper.Error.NotFound',
        'gverb'=> 'GET',
        'pverb'=> '',
        'middleware'=>''
    ],
    '/login' => [
        'target'=>'Panel.User.Login',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Login' => [
        'target'=>'Panel.User.Login',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Signup' => [
        'target'=>'Panel.User.Signup',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/signup' => [
        'target'=>'Panel.User.Signup',
        'gverb'=> 'GET',
        'pverb'=> 'POST',
        'middleware'=>''
    ],
    '/Documentation'=>[
        'target'=>'Main.Home.Documentation',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>''
    ],
    '/Panel'=>[
        'target'=>'Panel.Admin.Index',
        'gverb'=>'GET',
        'pverb'=>'',
        'middleware'=>'Panel.Admin.Index'
    ],
    '/panel'=>[
        'target'=>'Panel.Admin.Index',
        'gverb'=>'GET',
        'pverb'=>'',
        'middleware'=>'Panel.Admin.Index'
    ],
    '/Panel/NewPost'=>[
        'target'=>'Panel.Admin.NewPost',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>'Panel.Admin.NewPost'
    ],
    '/Panel/Newpost'=>[
        'target'=>'Panel.Admin.NewPost',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>'Panel.Admin.NewPost'
    ],
    '/panel/newpost'=>[
        'target'=>'Panel.Admin.NewPost',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>'Panel.Admin.NewPost'
    ],
    '/Panel/Users'=>[
        'target'=>'Panel.Admin.Users',
        'gverb'=>'GET',
        'pverb'=>'',
        'middleware'=>'Panel.Admin.Users'
    ],
    '/panel/users'=>[
        'target'=>'Panel.Admin.Users',
        'gverb'=>'GET',
        'pverb'=>'',
        'middleware'=>'Panel.Admin.Users'
    ],
    '/Test'=>[
        'target'=>'Test.Index.Call',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>''
    ],
    '/Testresponse'=>[
        'target'=>'Test.Index.Response',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>''
    ],
    '/Testcallback'=>[
        'target'=>'Test.Index.Callback',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>''
    ],
    '/Posts/'=>[
        'target'=>'Main.Home.Post',
        'gverb'=>'GET',
        'pverb'=>'',
        'middleware'=>'Main.Home.Post'
    ],
    '/posts/'=>[
        'target'=>'Main.Home.Post',
        'gverb'=>'GET',
        'pverb'=>'',
        'middleware'=>'Main.Home.Post'
    ],
    '/Panel/Posts'=>[
        'target'=>'Panel.Admin.Post',
        'gverb'=>'GET',
        'pverb'=>'',
        'middleware'=>'Panel.Admin.Post'
    ],
    '/Panel/Posts/Delete/'=>[
        'target'=>'Panel.Admin.PostDelete',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>'Panel.Admin.PostDelete'
    ],
    '/Panel/Posts/Update/'=>[
        'target'=>'Panel.Admin.PostUpdate',
        'gverb'=>'GET',
        'pverb'=>'POST',
        'middleware'=>'Panel.Admin.PostUpdate'
    ],
];