<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="Xenon Boostrap Admin Panel" />
	<meta name="author" content="" />
	
	<title>Xenon - Login</title>
    <?php
    session_start();
    $error=''; // Variable To Store Error Message
    if (isset($_POST['submit']))
    {
        if (empty($_POST['username']) || empty($_POST['password']))
        {
            $error = "Username or Password is invalid";
        }
        else
        {

            $Username = $_POST['username'];
            $Password = $_POST['password'];
            $Data = new Model\Repository\MainFunction\UserRepository();
            $Val = $Data->FindByUser($Username);
            $uResult = $Data->Username($Username);
            $pResult = $Data->Password($Password);
            if ($uResult == 1 && $pResult==1)
            {
                header("Location: /Panel");
                setcookie("Username",$Val['Values']['user_Firstname'],0);

            }
            else
            {
                header("Location: /Login");
            }
        }
    }
    //$_SESSION['username']='username';
    //$_SESSION['password']='password';
    //setcookie("username","username","0","","simplist.dev","true","true");
    $Adder = new Core\Requirement\oLoad("../../../..","Style","Script","Content");
    $Adder->Loader("css","Panel/fonts/fontawesome/css/font-awesome.min");
    $Adder->Loader("css","Panel/fonts/linecons/css/linecons");
    $Adder->Loader("css","Panel/bootstrap");
    $Adder->Loader("css","Panel/xenon-core");
    $Adder->Loader("css","Panel/xenon-forms");
    $Adder->Loader("css","Panel/xenon-components");
    $Adder->Loader("css","Panel/xenon-skins");
    $Adder->Loader("css","Panel/custom");
    $Adder->Loader("css","Panel/mytest");
    $Adder->Loader("js","Panel/jquery-1.11.1.min");

    /*$Adder->Loader("css","Panel/all");
    $Adder->Loader("css","Panel/all");
    $Adder->Loader("css","Panel/all");
    $Adder->Loader("css","Panel/all");*/
    ?>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	
	
</head>
<body class="page-body login-page" dir="rtl">

	
	<div class="login-container" dir="rtl" >
	
		<div class="row" dir="rtl">
		
			<div class="col-sm-6">
			
				<script type="text/javascript">
					jQuery(document).ready(function($)
					{
						// Reveal Login form
						setTimeout(function(){ $(".fade-in-effect").addClass('in'); }, 1);
						
						
						// Validation and Ajax action
						$("form#login").validate({
							rules: {
								username: {
									required: true
								},
								
								passwd: {
									required: true
								}
							},
							
							messages: {
								username: {
									required: 'Please enter your username.'
								},
								
								passwd: {
									required: 'Please enter your password.'
								}
							},
							
							// Form Processing via AJAX
							submitHandler: function(form)
							{
								show_loading_bar(70); // Fill progress bar to 70% (just a given value)
								
								var opts = {
									"closeButton": true,
									"debug": false,
									"positionClass": "toast-top-full-width",
									"onclick": null,
									"showDuration": "300",
									"hideDuration": "1000",
									"timeOut": "5000",
									"extendedTimeOut": "1000",
									"showEasing": "swing",
									"hideEasing": "linear",
									"showMethod": "fadeIn",
									"hideMethod": "fadeOut"
								};
									
								$.ajax({
									url: "data/login-check.php",
									method: 'POST',
									dataType: 'json',
									data: {
										do_login: true,
										username: $(form).find('#username').val(),
										passwd: $(form).find('#passwd').val(),
									},
									success: function(resp)
									{
										show_loading_bar({
											delay: .5,
											pct: 100,
											finish: function(){
												
												// Redirect after successful login page (when progress bar reaches 100%)
												if(resp.accessGranted)
												{
													window.location.href = 'dashboard-1.html';
												}
																							else
												{
													toastr.error("You have entered wrong password, please try again. User and password is <strong>demo/demo</strong> :)", "Invalid Login!", opts);
													$passwd.select();
												}
																						}
										});
										
																		}
								});
								
							}
						});
						
						// Set Form focus
						$("form#login .form-group:has(.form-control):first .form-control").focus();
					});
				</script>
				
				<!-- Errors container -->
				<div class="errors-container">
				
									
				</div>
				
				<!-- Add class "fade-in-effect" for login form effect -->
				<form method="post" role="form" id="login" class="login-form fade-in-effect">
					
					<div class="login-header text-right" dir="rtl">
						<a href="dashboard-1.html" class="logo" >
							<img src="assets/images/logo@2x.png" alt="" width="80" />
							<span>ورود</span>
						</a>
						
						<p>کاربر گرامی, برای دسترسی به منطقه مدیریت وارد شوید!</p>
					</div>
	
					
					<div class="form-group">
						<label class="control-label" for="username">نام کاربری</label>
						<input type="text" class="form-control input-dark" name="username" id="username" autocomplete="off" />
					</div>
					
					<div class="form-group">
						<label class="control-label" for="passwd">رمزینه</label>
						<input type="password" class="form-control input-dark" name="passwd" id="passwd" autocomplete="off" />
					</div>
					
					<div class="form-group">
						<button type="submit" class="btn btn-dark  btn-block text-right">
							ورود
							<i class="fa-lock"></i>
						</button>
					</div>
					
					<div class="login-footer">
						<a href="#">رمز خود را فراموش کردید؟</a>
						
						<div class="info-links">
							<a href="#">ToS</a> -
							<a href="#">حریم شخصی</a>
						</div>
						
					</div>
					
				</form>
				
				<!-- External login -->
				<div class="external-login" dir="rtl">
					<a href="#" class="facebook">
						<i class="fa-facebook"></i>
						ورود به فیس بوک
					</a>
					
					
					<a href="#" class="twitter">
						<i class="fa-twitter"></i>
						ورود به توییتر
					</a>
					
					<a href="#" class="gplus">
						<i class="fa-google-plus"></i>
						ورود به گوگل پلاس
					</a>
				</div>
				
			</div>
			
		</div>
		
	</div>



	<!-- Bottom Scripts -->
    <?php
    $Adder->Loader("js","Panel/bootstrap.min");
    $Adder->Loader("js","Panel/TweenMax.min");
    $Adder->Loader("js","Panel/resizeable");
    $Adder->Loader("js","Panel/joinable");
    $Adder->Loader("js","Panel/xenon-api");
    $Adder->Loader("js","Panel/xenon-toggles");
    $Adder->Loader("js","Panel/jquery-validate/jquery.validate.min");
    $Adder->Loader("js","Panel/toastr/toastr.min");
    $Adder->Loader("js","Panel/xenon-custom");
    $Adder->Loader("js","Panel/bootstrap.min");
    ?>

</body>
</html>