<?php
$Adder = new \Model\Repository\MainFunction\AssetsLoader();
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="object" property="og:type">
    <meta content="Simplist is a free & open-source framework for developing, creating & designing online blogs simply." name="description">
    <meta content="origin-when-cross-origin" name="referrer">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
    <link rel="shortcut icon" type="image/x-icon" href="../../../../Content/Shared/Logo.png" id="favicon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../../Content/Shared/Logo.png">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../../Content/Shared/Logo.png">
    <title>WELCOME TO SIMPLIST</title>
    <?php
    $Adder->Loader("css","Main/main");
    $Adder->Loader("css","Shared/Logos");
    $Adder->Loader("css","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css");
    $Adder->Loader("cs","product","http://getbootstrap.com/docs/4.0/examples/product");
    $Adder->Loader("js","Main/main");
    $Adder->Loader("js","jquery-3.2.1.slim.min","https://code.jquery.com");
    $Adder->Loader("js","popper.min","https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd");
    $Adder->Loader("js","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js");
    ?>
</head>
<body>
 <div>


     <div class="Container " style="text-align: center;vertical-align: middle;margin-top: 150px;">
     <a href="https://miladzandi.ir" target="_blank"><div class="Simplistlogo" >Simplist</div></a>
     <div class="MainText">WELCOME TO SIMPLIST</div>
     <div class="SubText">My name is <a href="https://miladzandi.ir" target="_blank">Milad Xandi</a> and I`m very happy because its useful for you.</div>
     <div class="SubText">You can download it from our <a href="https://gitlab.com/miladxandi/Simplist" target="_blank">Gitlab</a> repository and stay connected.</div>
     </div>
 </div>
 <footer class="container py-5">
     <div class="row">
         <div class="col-12 col-md">
             <?php $Adder->Loader("png","eastCloud","Shared",true,null,"eastCloud",24,24); ?>
             <small class="d-block mb-3 text-muted">© 2017-2018</small>
         </div>
         <div class="col-6 col-md">
             <h5>Features</h5>
             <ul class="list-unstyled text-small">
                 <li><a class="text-muted" href="#">Cool stuff</a></li>
                 <li><a class="text-muted" href="#">Random feature</a></li>
                 <li><a class="text-muted" href="#">Team feature</a></li>
                 <li><a class="text-muted" href="#">Stuff for developers</a></li>
                 <li><a class="text-muted" href="#">Another one</a></li>
                 <li><a class="text-muted" href="#">Last time</a></li>
             </ul>
         </div>
         <div class="col-6 col-md">
             <h5>Resources</h5>
             <ul class="list-unstyled text-small">
                 <li><a class="text-muted" href="#">Resource</a></li>
                 <li><a class="text-muted" href="#">Resource name</a></li>
                 <li><a class="text-muted" href="#">Another resource</a></li>
                 <li><a class="text-muted" href="#">Final resource</a></li>
             </ul>
         </div>
         <div class="col-6 col-md">
             <h5>Resources</h5>
             <ul class="list-unstyled text-small">
                 <li><a class="text-muted" href="#">Business</a></li>
                 <li><a class="text-muted" href="#">Education</a></li>
                 <li><a class="text-muted" href="#">Government</a></li>
                 <li><a class="text-muted" href="#">Gaming</a></li>
             </ul>
         </div>
         <div class="col-6 col-md">
             <h5>About</h5>
             <ul class="list-unstyled text-small">
                 <li><a class="text-muted" href="#">Team</a></li>
                 <li><a class="text-muted" href="#">Locations</a></li>
                 <li><a class="text-muted" href="#">Privacy</a></li>
                 <li><a class="text-muted" href="#">Terms</a></li>
             </ul>
         </div>
     </div>
 </footer>
</body>
</html>