<?php
$Add = new Core\Requirement\oLoad("../../../..","Style","Script","Content");

    if (isset($_COOKIE['Username']) &&($_COOKIE['Username']!=null||$_COOKIE['Username']!=""))

    {
        $Is_User_LoggedIn=true;
    }

    else

    {
        $Is_User_LoggedIn=false;
    }

?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="object" property="og:type">
    <meta content="Simplist is a free & open-source framework for developing, creating & designing online blogs simply." name="description">
    <meta content="origin-when-cross-origin" name="referrer">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
    <link rel="shortcut icon" type="image/x-icon" href="../../../../Content/Shared/Logo.png" id="favicon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../../Content/Shared/Logo.png">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../../Content/Shared/Logo.png">
    <title>WELCOME TO SIMPLIST</title>
    <?php
    $Add->Loader("css","Shared/Logos");
    $Add->Loader("css","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css");
    $Add->Loader("cs","product","http://getbootstrap.com/docs/4.0/examples/product");
    $Add->Loader("js","Main/main");
    $Add->Loader("css","Main/main");
    $Add->Loader("js","jquery-3.2.1.slim.min","https://code.jquery.com");
    $Add->Loader("js","popper.min","https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd");
    $Add->Loader("js","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js");
    ?>
</head>
<body>


    <!--  Menu -->
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">

                <?php if ($Is_User_LoggedIn): ?>
                    <a class="navbar-brand" href="/Panel">
                    <?php $Add->Loader("png",$_COOKIE['Username'],"Shared/Profile",true,false,"",30,30,null,"d-inline-block align-top"); ?>
                    </a>
                <?php else: ?>
                    <?php $Add->Loader("png","Logo","Shared",true,false,"Simplist",30,30,null,"d-inline-block align-top"); ?>
                <?php endif; ?>

            <?php if ($Is_User_LoggedIn): ?>
                <a class="navbar-brand" href="/Panel">Hello <?php echo $_COOKIE['Username']; ?></a>
            <?php else: ?>
                <a class="navbar-brand" href="/Login">Login</a>
            <?php endif; ?>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Aboutus">Aboutus</a>
                    </li>
                    <?php if ($Is_User_LoggedIn): ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Links
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#" target="_blank">Profile</a>
                                <a class="dropdown-item" href="#" target="_blank">Account</a>
                                <a class="dropdown-item" href="/Login" target="_blank">Logout</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="https://gitlab.com/miladxandi/Simplist" target="_blank">Direct Download</a>
                                <a class="dropdown-item" href="https://gitlab.com/miladxandi/Simplist" target="_blank">GITLAB</a>

                            </div>
                        </li>
                    <?php else: ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Links
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="https://gitlab.com/miladxandi/Simplist" target="_blank">Direct Download</a>
                                <a class="dropdown-item" href="https://gitlab.com/miladxandi/Simplist" target="_blank">GITLAB</a>
                            </div>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </nav>
    </div>


    <!--  Content -->
    <div>
        <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
            <a href="https://simplist.ir" target="_blank"><?php $Add->Loader("png","Logo","Shared",true,false,"Simplist",100,100) ?></a>
            <div class="MainText ">WELCOME TO SIMPLIST </div>
        </div>
    </div>

    <div>
        <div>
            <div class="SubText PurpText ">Our group is <a href="https://estcloud.ir" target="_blank" class="DefinedRoya PurpStyle">estCloud LLC.</a> and your trust made us happy.</div>
            <div class="SubText PurpText ">You can download our the project from <a href="https://gitlab.com/miladxandi/Simplist" class="PurpStyle" target="_blank"> our Gitlab </a> and stay connected with us.</div>
        </div>
    </div>

    <!--  Footer -->
    <footer class="container py-5">
        <div class="row">
            <div class="col-12 col-md">
                <a href="http://eastcloud.ir"><?php $Add->Loader("png","eastCloud","Shared",true,false,"eastCloud",24,24); ?></a>
                <small class="d-block mb-3 text-muted">© 2017-2018</small>
            </div>
            <div class="col-6 col-md">
                <h5>New Features</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/Feacture/Driver">Choose Driver</a></li>
                    <li><a class="text-muted" href="/Feacture/Hash">Make it Hash!</a></li>
                    <li><a class="text-muted" href="/Feacture/SUS">Sunshine Sec</a></li>
                    <li><a class="text-muted" href="/Feacture/Observer">Observer</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Resources & Versions</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/Res">Resource</a></li>
                    <li><a class="text-muted" href="/Download/Versions">Stable Versions</a></li>
                    <li><a class="text-muted" href="/Dev/Versions">Dev Versions</a></li>
                    <li><a class="text-muted" href="/Download/Versions/Latest">Download Lates</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Develop</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="https://github.com/miladxandi/Simplist">Github</a></li>
                    <li><a class="text-muted" href="/Documentation/Education">Education</a></li>
                    <li><a class="text-muted" href="/Documentation">Documentations</a></li>
                    <li><a class="text-muted" href="/Services">Services</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/Team">Team</a></li>
                    <li><a class="text-muted" href="/Locations">Locations</a></li>
                    <li><a class="text-muted" href="/Privacy">Privacy</a></li>
                    <li><a class="text-muted" href="/Terms">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>


</body>
</html>