<?php \View\View\Shared\MainLayouts::_Header(); ?>
<title>SIMPLIST - Call</title>
</head>
<?php \View\View\Shared\MainLayouts::_Menu(); ?>


<?php
session_start();
$error = ''; // Variable To Store Error Message

if (isset($_POST['submit'])) {

    $Data = new \Model\Repository\MainFunction\UserRepository();
    $Name = $_POST["PostName"];
    $Url = $_POST["PostUrl"];
    $Content = $_POST["PostContent"];
    $Author = $_POST["PostAuthor"];
    $Insert = $Data->InsertPost($Name,$Url,$Content,$Author);
    if ($Insert == 1) {
        header("Location: /Callresponse");
    } else {
        header("Location: /Call");

    }
}
$Add = new Core\Requirement\oLoad("../../..", "Style/Panel", "Script/Panel", "Style/Panel");
$Add->Loader("css", "fonts/fontawesome/css/font-awesome.min");
$Add->Loader("css", "fonts/linecons/css/linecons");
$Add->Loader("css", "bootstrap.min", "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css", false);
$Add->Loader("css", "mytest");
?>


<?php print_r(PDO::getAvailableDrivers()); ?>


<div style="margin-top:100px;margin-left:100px;margin-right:100px;">
    <form method="Post" role="form" action="">

        <div class="form-group">
            <label for="PostName">Post Name</label>
            <input type="text" class="form-control" name="PostName" id="PostName" required
                   placeholder="Title">
        </div>
        <div class="form-group">
            <label for="PostUrl">Post Url</label>
            <input type="text" class="form-control" name="PostUrl" id="PostUrl" required
                   placeholder="Specified URL">
        </div>
        <div class="form-group">
            <label for="Lastname">Last Name</label>
            <textarea class="form-control" name="PostContent" id="PostContent" required
                   placeholder="Content">
            </textarea>
        </div>
        <div class="form-group">
            <label for="PostAuthor">National Code</label>
            <input type="text" class="form-control" name="PostAuthor" id="PostAuthor" value="<?php $_COOKIE['Firstname'] ?>" required
                   placeholder="Enter national code">
        </div>

        </div>

        <button type="submit" name="submit" id="submit" class="btn btn-primary">Post</button>

    </form>
</div>
<?php \View\View\Shared\MainLayouts::_Footer(); ?>
