<?php


namespace Model\Connection;


class Database
{
    protected $ConnectionString;
    public function __construct()
    {
        Try {
            $this->ConnectionString = new \PDO("mysql:host=localhost;dbname=simplist_simplist;charset=utf8", "root", "");
            //$this->ConnectionString = new \PDO("mysql:host=localhost;dbname=simplist_simplist;charset=utf8", "simplist_simple", "Milad&0937");
        }
        catch (\PDOException $exception)
        {
            $exception->getMessage();
        }
    }
}