<?php
/**
 * Created by PhpStorm.
 * User: farva
 * Date: 20/03/2018
 * Time: 10:43 PM
 */

namespace Controller\Test;


use Route\Show\View;

class IndexController
{
    public function Call($Querry_String)
    {
        $Viewbag=['QuerryString'=>$Querry_String];
        View::Process("Test.Home.Call",$Viewbag);
    }
    public function Response()
    {
        View::Process("Test.Home.Response");
    }
    public function Callback()
    {
        View::Process("Test.Home.Callback");
    }
}