<?php
/**
 * Created by PhpStorm.
 * User: farva
 * Date: 04/02/2018
 * Time: 03:24 PM
 */

namespace View\View\Shared;


class MainLayouts
{
    public static function _Header()
    {
        include "Main/_HeaderLayout.phtml";
    }
    public static function _Menu()
    {
        include "Main/_MenuLayout.phtml";
    }
    public static function _Footer()
    {
        include "Main/_FooterLayout.phtml";
    }
}
class PanelLayouts
{
    public static function _Header()
    {
    }
    public static function _Setting()
    {
    }
    public static function _Siderbar()
    {
    }
    public static function _Footer()
    {
    }
}