<?php

namespace Controller\Main;


use Route\Show\View;

class HomeController
{
    private $Username;

    public function __construct()
    {
        //$this->Username=new UserRepository();
    }
    public function Index()
    {
        //$Viewbag="SIMPLIST";
        View::Process("Main.Home.Index");
    }
    public function Aboutus()
    {
        View::Process("Main.Home.Aboutus");
    }
    public function Documentation()
    {
        View::Process("Main.Home.Documentation");
    }

}