<body>


<!--  Menu -->
<div>

    <?php
    $Add = new Core\Requirement\oLoad("../../..","Style/Main","Script/Main","Content/Main");
    if (isset($_COOKIE['Firstname']) &&($_COOKIE['Firstname']!=null||$_COOKIE['Firstname']!=""))
    {
        $Is_User_LoggedIn=true;
    }

    else

    {
        $Is_User_LoggedIn=false;
    }
    ?>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <?php if ($Is_User_LoggedIn): ?>
                <?php if(file_exists("../../Content/Shared/Profile/".$_COOKIE['Firstname'].".png")==1 ||file_exists("../../Content/Shared/Profile/".$_COOKIE['Firstname'].".png")==true)
                {
                    $Add->Loader("png",$_COOKIE['Firstname'],"Shared/Profile",true,false,"",30,30,null,"d-inline-block align-top");
                }
                else
                {
                    $Add->Loader("png","Avatar","Shared/Profile",true,false,"",30,30,null,"d-inline-block align-top");
                }
                ?>
            <?php else: ?>
                <?php $Add->Loader("png","Logo","Shared",true,false,"eastCloud",30,30,null,"d-inline-block align-top"); ?>
            <?php endif; ?>
        </a>
        <?php if ($Is_User_LoggedIn): ?>
            <a class="navbar-brand" href="/Panel">Hello <?php echo $_COOKIE['Firstname']; ?></a>

        <?php else: ?>
            <a class="navbar-brand" href="/Login">Login</a>
        <?php endif; ?>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Aboutus">Aboutus</a>
                </li>
                <?php if ($Is_User_LoggedIn): ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Links
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/Panel" >Panel</a>
                            <a class="dropdown-item" href="/Panel/Profile" >Profile</a>
                            <?php if ($_COOKIE['Username']=="miladxandi"): ?>
                            <a class="dropdown-item" href="/Panel/NewPost" >New Post</a>
                            <a class="dropdown-item" href="/Panel/Posts" >Posts</a>
                                <a class="dropdown-item" href="/Panel/NewUrl" >New Links</a>
                                <a class="dropdown-item" href="/Panel/Url" >Links</a>
                            <a class="dropdown-item" href="/Panel/Users" >Users</a>
                            <?php endif; ?>
                            <a class="dropdown-item" href="/Login">Logout</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/Simplist.zip" target="_blank">Direct Download</a>
                            <a class="dropdown-item" href="https://github.com/miladxandi/Simplist" target="_blank">GitHub</a>

                        </div>
                    </li>
                <?php else: ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Links
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/Simplist.zip" target="_blank">Direct Download</a>
                            <a class="dropdown-item" href="https://github.com/miladxandi/Simplist" target="_blank">GitHub</a>
                        </div>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </nav>
</div>