<!doctype html>
<html lang="fa">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <meta name="description" content="Welcome eastCloud service.
a new service to share and send your files with any extension">
    <meta name="keywords" content="فضا ابری
ابر شرقی
eastCloud
eastcloudmedia
eastcloud media
eastCloud
eastCloud Media
eastcloud.ir
ابرشرقی
ابر شرقی. آی ار
فضای ابری ایران
فضا ابری ایرانیان
ذخیره سازی ابری
بک آپ ابری">
    <meta name="author" content="Milad Xandi">
    <meta name="categories" content="Cloud Service">
    <meta name="robots" content="index, follow">
    <meta name="revisit-after" content="1 day">
    <meta property="og:description" content="Welcome eastCloud service.
a new service to share and send your files with any extension">
    <meta property="og:type" content="business.business">
    <meta property="og:image" content="http://www.eastcloud.ir/../../../Content/Main/favicon.png">
    <meta name="generator" content="Microsoft - http://www.microsoft.com">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>eastCloud | Not Found</title>
    <meta property="og:title" content="eastCloud | Not Found">
    <?php
    $Adder = new Core\Requirement\oLoad("../../..","Style/Panel","Script/Panel","Content/");
    $Adder->Loader("css","Main/main");
    $Adder->Loader("js","Main/main");
    $Adder->Loader("css","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css","false");
    $Adder->Loader("js","jquery-3.2.1.slim.min","https://code.jquery.com","false");
    $Adder->Loader("js","popper.min","https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd","false");
    $Adder->Loader("js","bootstrap.min","https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js","false");
    ?>
</head>
<body>
<div>
    <?php
        print '<div class="Container" style="text-align: center;vertical-align: middle;padding-top: 300px;">';
        print '<div class="MainText" style="text-align: center;vertical-align: middle;font-size: 100px;font-family: '.'Calibri Light'.';">Bad Request</div>';
        print '</div>';
    ?>
</div>
</body>
</html>
