<?php \View\View\Shared\MainLayouts::_Header(); ?>
<title>Requested Method Not Allowed</title>
</head>
<body>
<div>
    <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
        <a href="https://simplist.ir" ><img src="../../../../Content/Shared/Logo.png" class="" style="" alt="Simplist" width="100px" height="100px"></a>
        <div class="MainText ">Requested Method Not Allowed</div>
    </div>
</div>
</body>
</html>
