<?php


namespace Model\Repository;
use Illuminate\Database\Capsule;

abstract class BaseRepository
{
    protected static $Model;
    public function __construct()
    {
        //$this->rStatement=new Connection\Statement();
    }
    public function Find(int $ID)
    {
        return self::$Model::Find($ID);
    }

    public function All()
    {

    }

    public function Delete(int $ID)
    {

    }

    public function Create(array $Data)
    {

    }

    public function Update(int $ID,array $Data)
    {

    }

}