<?php


namespace Model\Repository;
use Model\Connection;
//use Illuminate\Database\Capsule;

abstract class BaseRepository
{
    protected static $Model;
    protected $rStatement;
    public $Table;
    protected $PrimaryKey;
    protected $uName;
    protected $uPass;
    protected $uMail;
    protected $uToken;
    public function __construct()
    {
        $this->rStatement=new Connection\Statement();
    }
    public function Find(int $ID)
    {
        $Result = $this->rStatement->Commander("SELECT * FROM {$this->Table} WHERE {$this->PrimaryKey}={$ID}");
        return $Result->fetch(\PDO::FETCH_ASSOC);
    }
    public function All()
    {
        $Result = $this->rStatement->Commander("SELECT * FROM {$this->Table}");
        return $Result->fetchAll(\PDO::FETCH_ASSOC);
    }

}