<?php


namespace Model\Repository;
use Model\Connection;
//use Illuminate\Database\Capsule;

abstract class BaseRepository
{
    protected static $Model;
    protected $rStatement;
    protected $Table;
    protected $PrimaryKey;
    public function __construct()
    {
        $this->rStatement=new Connection\Statement();
    }
    public function Find(int $ID)
    {
        $Result = $this->rStatement->Commander("SELECT * FROM {$this->Table} WHERE {$this->PrimaryKey}={$ID} ");
        return $Result->fetch(\PDO::FETCH_ASSOC);
    }

    public function All()
    {

    }

    public function Delete(int $ID)
    {

    }

    public function Create(array $Data)
    {

    }

    public function Update(int $ID,array $Data)
    {

    }

}