<?php \View\View\Shared\MainLayouts::_Header(); ?>
    <title>SIMPLIST - ABOUT US</title>
    </head>
<?php \View\View\Shared\MainLayouts::_Menu(); ?>
<!--  Content -->
<div>
    <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
            <a href="https://simplist.ir"><img src="../../../../Content/Shared/Logo.png" class="" style="" alt="Simplist" width="100px" height="100px"></a>
        <div class="MainText ">What is SIMPLIST?</div>
    </div>
</div>

<div>
    <div>
        <div class="SubText PurpText "> Simplist is a mini framework based on PHP language for small projects.</div>
        <div class="SubText PurpText "> We strongly suggest our framework for personal blogs, news agencies & human resource management.</div>
    </div>
</div>

    <div>
        <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
            <a href="https://miladzandi.ir"><div class="Simplistlogo">Simplist</div></a>
            <div class="MainText ">Services</div>
        </div>
    </div>
    <div>
        <div>
            <div class="SubText PurpText "> Just like any other PHP framework we started this project based on MVC architecture with the featured services like <code class="Code" >$Add->Loader</code> , <code class="Code" >gVerb | pVerb</code> , SharedLayouts, Middlewares & pre-defined security.</div>
            <div class="SubText PurpText "> Everything in simplist is as simple as installing it on your server!</div>
            <div class="SubText PurpText "> <a href="mailto:info@miladzandi.ir" target="_blank" class="PurpStyle"> Want to help in development? </a> </div>
        </div>
    </div>

<?php \View\View\Shared\MainLayouts::_Footer(); ?>