<?php \View\View\Shared\MainLayouts::_Header(); ?>
    <title>SIMPLIST - ABOUT US</title>
<?php \View\View\Shared\MainLayouts::_Menu(); ?>
<!--  Content -->
<div>
    <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
        <a href="https://miladzandi.ir"><div class="Simplistlogo">Simplist</div></a>
        <div class="MainText ">WELCOME TO SIMPLIST</div>
    </div>
</div>

<div>
    <div>
        <div class="SubText PurpText ">Our group is <a href="https://estcloud.ir" target="_blank" class="DefinedRoya PurpStyle">estCloud LLC.</a> and your trust made us happy.</div>
        <div class="SubText PurpText ">You can download our the project from <a href="https://gitlab.com/miladxandi/Simplist" class="PurpStyle" target="_blank"> our Gitlab </a> and stay connected with us.</div>
    </div>
</div>


<?php \View\View\Shared\MainLayouts::_Footer(); ?>