<?php \View\View\Shared\MainLayouts::_Header(); ?>
    <title>SIMPLIST - ABOUT US</title>
    </head>

<?php \View\View\Shared\MainLayouts::_Menu(); ?>
<!--  Content -->
    <div class="parallax w3-display-container w3-opacity-min" id="home">
        <div class="w3-display-middle" style="white-space:nowrap;">
            <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">Welcome to Simplist</span>
        </div>
    </div>
    <div id="Index">
    <div>
        <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
            <a href="https://eastcloud.ir/Simplist"><img src="../../../../Content/Shared/Logo.png" class="" style="" alt="Simplist" width="100px" height="100px"></a>
            <div class="MainText ">What is SIMPLIST?</div>
        </div>
    </div>

    <div>
        <div>
            <div class="SubText PurpText FitLayout" > Simplist is a mini framework based on PHP language for small projects.</div>
            <div class="SubText PurpText FitLayout" > We strongly suggest our framework for personal blogs, news agencies & human resource management.</div>
        </div>
    </div>

    <div>
        <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
            <a href="https://miladzandi.ir"><div class="Simplistlogo">Simplist</div></a>
            <div class="MainText ">Services</div>
        </div>
    </div>
    <div>
        <div>
            <div class="SubText PurpText FitLayout" > Just like any other PHP framework we started this project based on MVC architecture with the featured services like <code class="Code" >$Add->Loader</code> , <code class="Code" >gVerb | pVerb</code> , SharedLayouts, Middlewares & pre-defined security.</div>
            <div class="SubText PurpText FitLayout" > Everything in simplist is as simple as installing it on your server!</div>
            <div class="SubText PurpText FitLayout" > <a href="mailto:info@miladzandi.ir" target="_blank" class="PurpStyle"> Want to be a development contributor? </a> </div>
        </div>
    </div>
</div>

<?php \View\View\Shared\MainLayouts::_Footer(); ?>