<?php \View\View\Shared\MainLayouts::_Header(); ?>
    <title>SIMPLIST - Documentations</title>
    </head>
<?php \View\View\Shared\MainLayouts::_Menu(); ?>

<div>
    <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
        <a href="https://simplist.ir" ><img src="../../../../Content/Shared/Logo.png" class="" style="" alt="Simplist" width="100px" height="100px"></a>
        <div class="MainText ">Documentation</div>
    </div>
</div>
<div>
    <div>
        <div class="SubText PurpText FitLayout">
        This is a very simple documentation for the Simplist project.
        we want to teach you, how this project working on your server!
        </div>
    </div>
    <div class="alert alert-dark FitLayout" role="article">
        #Getting Started
    </div>

</div>
<?php \View\View\Shared\MainLayouts::_Footer(); ?>
