<?php \View\View\Shared\MainLayouts::_Header(); ?>
    <title>SIMPLIST - Home</title>
    </head>

<?php \View\View\Shared\MainLayouts::_Menu(); ?>
    <div class="parallax w3-display-container w3-opacity-min" id="home">
        <div class="w3-display-middle" style="white-space:nowrap;">
            <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">Welcome to Simplist</span>
        </div>
    </div>
    <div id="Index">
    <div class="Container">
        <div class="row">
            <div class="col">
                <div style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
                    <a href="https://eastcloud.ir/Simplist">
                        <img src="../../../Content/Shared/Logo.png" class="" style="" alt="Simplist" width="100px"
                             height="100px">
                    </a>
                    <div class="MainText ">WELCOME TO SIMPLIST</div>
                </div>
            </div>
        </div>
        <div >
            <div class="SubText PurpText FitLayout">
                <br>
                <div class="SubText PurpText FitLayout">Our group is <a href="https://eastcloud.ir" target="_blank"
                                                                        class="DefinedRoya PurpStyle">estCloud LLC.</a>
                    and your
                    trust
                    made us happy.
                </div>
                <div class="SubText PurpText FitLayout">You can download our the project from <a
                            href="https://github.com/eastCloudmedia/SimplistFramework" class="PurpStyle" target="_blank"> our
                        Github </a> and
                    stay connected with us.
                </div>
                <div class="SubText PurpText FitLayout">What is <span
                            style="color: #9756B3;font-weight: bold">Simplist</span>?<a
                            href="/Aboutus" class="PurpStyle"> Read More </a></div>
                </br>
                <a href="https://eastcloudmedia.github.io/SimplistFramework/" target="_blank">
                    <button type="button" class="btn btn-outline-secondary">Get Started</button>
                </a>
                <p id="Start"></p>
            </div>
        </div>
        </br>
        <div class="col-xs-12">
            <div class="row FitLayout">
            <div class="SubText PurpText FitLayout">
                <div class="Container">
                    <div class="row">
                        <?php
                        $Data = $Viewbag['PostInfo'];
                        $IMG = 1;
                        $Add = new Core\Requirement\oLoad("../../..", "Style/Main", "Script/Main", "Content/Main");
                        if ($Viewbag['PostInfo']!= null):
                        foreach ($Data as $Post): ?>
                            <div class="col-sm-6" style="height: max-content">
                                <div class="jumbotron">
                                    <a href="/Posts/?url=<?php echo $Post['Post_Url'] ?>">
                                        <img src="<?php
                                echo "../../../".$Post['Post_Image'];
                                ?>" alt="<?php echo $Post['Post_Name'] ?>" width="300px" height="200px">
                                    </a>

                                    <h1 class="display-4 PostTitle"><?php echo $Post['Post_Name'] ?></h1>
                                    <p class="lead PostContent"><?php echo $Post['Post_Summary'] ?> ...</p>
                                    <hr class="my-4 ">
                                    <p class="PostAuthor">نویسنده: <?php echo $Post['Post_Author'] ?></p>
                                    <p class="lead">
                                        <a class="btn btn-primary btn-lg"
                                           href="/Posts/?url=<?php echo $Post['Post_Url'] ?>"
                                           role="button">Learn more</a>
                                    </p>
                                </div>
                            </div>

                        <?php endforeach; ?>
                        <?php else: ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    </div>
<?php \View\View\Shared\MainLayouts::_Footer(); ?>