<?php \View\View\Shared\MainLayouts::_Header(); ?>
    <title>SIMPLIST - Home</title>
    </head>
<?php \View\View\Shared\MainLayouts::_Menu(); ?>
<!--  Content -->
    <div>
        <div class="Container " style="text-align: center;vertical-align: middle;margin-bottom: 50px;margin-top: 50px;">
            <a href="https://simplist.ir" target="_blank"><img src="../../../../Content/Shared/Logo.png" class="" style="" alt="Simplist" width="100px" height="100px"></a>
            <div class="MainText ">WELCOME TO SIMPLIST </div>
        </div>
    </div>

    <div>
        <div>
            <div class="SubText PurpText ">Our group is <a href="https://eastcloud.ir" target="_blank" class="DefinedRoya PurpStyle">estCloud LLC.</a> and your trust made us happy.</div>
            <div class="SubText PurpText ">You can download our the project from <a href="https://gitlab.com/miladxandi/Simplist" class="PurpStyle" target="_blank"> our Gitlab </a> and stay connected with us.</div>
            <div class="SubText PurpText ">What is <span style="color: #9756B3;font-weight: bold">Simplist</span>?<a href="https://gitlab.com/miladxandi/Simplist" class="PurpStyle" target="_blank"> Read More </a></div>
        </div>
    </div>

<?php \View\View\Shared\MainLayouts::_Footer(); ?>