<?php \View\View\Shared\MainLayouts::_Header(); ?>
<?php $PostInfo = $Viewbag['PostInfo'][0]; ?>
    <title>SIMPLIST - <?php echo $PostInfo['Post_Name']; ?></title>
    </head>
<?php \View\View\Shared\MainLayouts::_Menu(); ?>
    <!--  Content -->
        <div class="Container">
            <div class="row">
                <div class="col-12">
                    <div class="jumbotron">
                        <img src="<?php
                                echo "../../../".$PostInfo['Post_Image'];
                                ?>" alt="<?php echo $PostInfo['Post_Name'] ?>" width="300px" height="200px">
                        <h1 class="display-4 PostTitle"><?php echo $PostInfo['Post_Name']; ?></h1>
                        <p class="lead PostContent"><?php echo $PostInfo['Post_Content']; ?></p>
                        <hr class="my-4 ">
                        <p class="PostAuthor"> نویسنده: <?php echo $PostInfo['Post_Author']; ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>


<?php \View\View\Shared\MainLayouts::_Footer(); ?>